### ISSUE TITLE
Slack API를 이용해 특정 채널의 특정 user의 message를 가져올 수 있는지 확인

### ISSUE THREAD

**Issue by ssaru** [dl4ab/DFAB-Trello-Slackbot#5]

**Comment by ssaru** [comment]
![concept](https://user-images.githubusercontent.com/13328380/46663986-9660f800-cbfa-11e8-98a4-e2ba704c30c0.png)

**Comment by ssaru** [comment]
![user_scenario](https://user-images.githubusercontent.com/13328380/46664034-bb556b00-cbfa-11e8-9fc5-e3370962a9a0.png)

**Comment by Curt-Park** [comment]
트렐로 보드를 이용하는 까닭은 생성한 카드들을 다시금 살펴보고, 또한 상태가 변한 카드들을 직접 손으로 이동시키면서 전반적 일정들을 인지의 영역으로 끌어올리는 것에 있습니다. 만약 daily log 내용만으로 trello가 자동적으로 갱신된다면 그러한 효과들은 상당히 반감될 것 같습니다. 그래서 저는 슬랙 채널보다 트렐로 보드가 우선적으로 운영되어야 한다고 생각합니다. (채널은 단순히 트렐로의 현황을 보여주는 의도) 더불어 제시하신 기능들이 제공된다면 혹자들은 굳이 트렐로를 이용할 필요를 못느끼실 것 같은데, 이 부분들은 어떻게 생각하시나요?
